version: '3.3'

services:

  gis-api:
    container_name: gis-api
    build: 
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/backend
      - /backend/node_modules
    networks:
      - app
    ports:
      - 8080:8080
    restart: always

  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    networks:
      - app

  pgadmin:
    image: dpage/pgadmin4:6.18
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_LISTEN_PORT: $PGADMIN_LISTEN_PORT
    ports:
      - $PGADMIN_LISTEN_PORT:$PGADMIN_LISTEN_PORT
    volumes:
      - ./data//nest-plain-pg:/var/lib/pgadmin
    networks:
      - app

networks:
  app:
    driver: bridge
